### ISSUE TITLE
Error: Unexpected end of JSON input (https取得完整的response之前意外终止连接)

### ISSUE THREAD

**Issue by Billyzou0741326** [Billyzou0741326/bilibili-live-monitor-js#1]
向API发送请求有低概率中途关闭连接
- [x] 重写`bilibili.js`，将request发送统一放入一个方法里
- [x] ~~进行忽略~~
- [x] 检测到出错时重现request
- [x] 限制请求数量 （1秒8次）
   
`Unexpected token in JSON` （已解决）
- [x] 重启TCP连接（一次解决）

**Comment by findmio** [comment]
有一个小的问题，一直重连，但是还可以监听到抽奖
![image](https://img11.360buyimg.com/uba/jfs/t1/106024/8/3051/35835/5ddbce25E65087abf/ad2825e473e04a77.png)

**Comment by Billyzou0741326** [comment]
> 有一个小的问题，一直重连，但是还可以监听到抽奖
> ![image](https://camo.githubusercontent.com/c176ac5afd638dbd85cfd3e490ff0f890a8f54ef/68747470733a2f2f696d6731312e333630627579696d672e636f6d2f7562612f6a66732f74312f3130363032342f382f333035312f33353833352f35646462636532354536353038376162662f616432383235653437336530346137372e706e67)

这个算是大问题 我本来是打算修正一次就解决的 一直刷屏就不太对了…

**Comment by Billyzou0741326** [comment]
比较难办的是我这边很难可靠地重现出错误… 如果能重现出来 至少可以避免重连刷屏

**Comment by Billyzou0741326** [comment]
小概率：多个房间同时出错导致刷屏
高概率：单个房间不断重连失败 没能解决error

**Comment by findmio** [comment]
> 比较难办的是我这边很难可靠地重现出错误… 如果能重现出来 至少可以避免重连刷屏

client 端也停掉了
![image](https://img11.360buyimg.com/uba/jfs/t1/50185/10/16511/32712/5ddc00f1Eea9dfb68/7e506abd0b661d26.png)

**Comment by Billyzou0741326** [comment]
> > 比较难办的是我这边很难可靠地重现出错误… 如果能重现出来 至少可以避免重连刷屏
> 
> client 端也停掉了
> ![image](https://camo.githubusercontent.com/d67b8b356eed75be41456c78d54e782699a436e4/68747470733a2f2f696d6731312e333630627579696d672e636f6d2f7562612f6a66732f74312f35303138352f31302f31363531312f33323731322f35646463303066314565613964666236382f376535303661626430623636316432362e706e67)

这个是我的错 被412风控了（短时间内向b站发送太多请求 ip地址被暂时黑名单了）
Python版有控制请求数量，这边因为时间比较赶我没写出来… 很大可能是这边请求量过大导致的

**Comment by Billyzou0741326** [comment]
Python版用了两个月没出现这种情况 果然JS版要加紧写控制请求数量的逻辑呢
```
[2019-11-25 08:10:04]    aiohttp ClientError: 412, message='Precondition Failed', url='https://api.live.bilibili.com/i/api/taskInfo
[2019-11-25 08:10:04]    aiohttp ClientError: 412, message='Precondition Failed', url='https://api.live.bilibili.com/User/userOnlineHeart
[2019-11-25 08:10:04]    aiohttp ClientError: 412, message='Precondition Failed', url='https://api.live.bilibili.com/User/userOnlineHeart
[2019-11-25 08:10:04]    aiohttp ClientError: 412, message='Precondition Failed', url='https://api.live.bilibili.com/i/api/taskInfo
[2019-11-25 08:10:04]    aiohttp ClientError: 412, message='Precondition Failed', url='https://api.live.bilibili.com/User/userOnlineHeart
[2019-11-25 08:10:04]    aiohttp ClientError: 412, message='Precondition Failed', url='https://api.live.bilibili.com/User/userOnlineHeart
[2019-11-25 08:10:04]    aiohttp ClientError: 412, message='Precondition Failed', url='https://api.live.bilibili.com/i/api/taskInfo
[2019-11-25 08:10:04]    aiohttp ClientError: 412, message='Precondition Failed', url='https://api.live.bilibili.com/i/api/taskInfo
[2019-11-25 08:10:04]    aiohttp ClientError: 412, message='Precondition Failed', url='https://api.live.bilibili.com/User/userOnlineHeart
[2019-11-25 08:10:04]    aiohttp ClientError: 412, message='Precondition Failed', url='https://api.live.bilibili.com/User/userOnlineHeart
[2019-11-25 08:10:04]    aiohttp ClientError: 412, message='Precondition Failed', url='https://api.live.bilibili.com/i/api/taskInfo
[2019-11-25 08:10:04]    aiohttp ClientError: 412, message='Precondition Failed', url='https://api.live.bilibili.com/i/api/taskInfo
[2019-11-25 08:10:05]    aiohttp ClientError: 412, message='Precondition Failed', url='https://api.live.bilibili.com/i/api/taskInfo
[2019-11-25 08:10:05]    aiohttp ClientError: 412, message='Precondition Failed', url='https://api.live.bilibili.com/i/api/taskInfo
[2019-11-25 08:10:05]    aiohttp ClientError: 412, message='Precondition Failed', url='https://api.live.bilibili.com/i/api/taskInfo
[2019-11-25 08:10:06]    aiohttp ClientError: 412, message='Precondition Failed', url='https://api.live.bilibili.com/i/api/taskInfo
```

**Comment by Billyzou0741326** [comment]
翻了翻log确认了一下 
连接数3700左右被412风控了

已经写好了请求控制 看下今天的情况吧

**Comment by like044041** [comment]
> 翻了翻log确认了一下
> 连接数3700左右被412风控了
> 
> 已经写好了请求控制 看下今天的情况吧

老哥,刚更新就打不开了
![20191126043431](https://user-images.githubusercontent.com/33434924/69575877-1ff1a600-1006-11ea-906c-386b2048c1cb.png)

**Comment by Billyzou0741326** [comment]
> > 翻了翻log确认了一下
> > 连接数3700左右被412风控了
> > 已经写好了请求控制 看下今天的情况吧
> 
> 老哥,刚更新就打不开了
> ![20191126043431](https://user-images.githubusercontent.com/33434924/69575877-1ff1a600-1006-11ea-906c-386b2048c1cb.png)

嗯是我的错 多加了括号23333
又更新了一次 这次应该可以了吧

**Comment by Billyzou0741326** [comment]
> 小概率：多个房间同时出错导致刷屏
> 高概率：单个房间不断重连失败 没能解决error

大致推测出了TCP连接重启的刷屏原因了，可能性比较高但没法确定
发送关闭请求后数据流还在持续推送(而且数量非常多) 于是刷屏...
但这绝对是异常状况 一米哇嘎乃

**Comment by like044041** [comment]
> > 小概率：多个房间同时出错导致刷屏
> > 高概率：单个房间不断重连失败 没能解决error
> 
> 大致推测出了TCP连接重启的刷屏原因了，可能性比较高但没法确定
> 发送关闭请求后数据流还在持续推送(而且数量非常多) 直接导致于是刷屏...
> 但这绝对是异常状况 一米哇嘎乃

比原来的稳定多了,就是会触发风控,昨天触发了2次,反而快12点大波大波的抽奖时并没有触发风控,然后就是这个TCP连接重启.

**Comment by Billyzou0741326** [comment]
> > > 小概率：多个房间同时出错导致刷屏
> > > 高概率：单个房间不断重连失败 没能解决error
> > 
> > 
> > 大致推测出了TCP连接重启的刷屏原因了，可能性比较高但没法确定
> > 发送关闭请求后数据流还在持续推送(而且数量非常多) 直接导致于是刷屏...
> > 但这绝对是异常状况 一米哇嘎乃
> 
> 比原来的稳定多了,就是会触发风控,昨天触发了2次,反而快12点大波大波的抽奖时并没有触发风控,然后就是这个TCP连接重启.

TCP连接重启是今天打算重点测试的 这个异常是要逼死强迫症啊hhh
风控已经处理了 下午/晚上那会儿看下效果
TCP问题嗯.... 看看等弹幕高峰期会不会再次触发吧 目前的情况没法对症下药

**Comment by Billyzou0741326** [comment]
Update：测试没能通过，不过原因找到了（果然是我的错2333） 等下merge修复版本，明天继续测试

**Comment by like044041** [comment]
> Update：测试没能通过，不过原因找到了（果然是我的错2333） 等下merge修复版本，明天继续测试

神奇的是,我今天没出现这个错误

**Comment by Billyzou0741326** [comment]
> > Update：测试没能通过，不过原因找到了（果然是我的错2333） 等下merge修复版本，明天继续测试
> 
> 神奇的是,我今天没出现这个错误

虽然不是最佳方案 但我强行压制了错误...

**Comment by Billyzou0741326** [comment]
之前的问题是重启连接后没重置原来的弹幕容器 所以一直Error...
两行代码的问题 用了整整两天233333

**Comment by like044041** [comment]
> 之前的问题是重启连接后没重置原来的弹幕容器 所以一直Error...
> 两行代码的问题 用了整整两天233333

老哥NB

**Comment by Billyzou0741326** [comment]
> > 之前的问题是重启连接后没重置原来的弹幕容器 所以一直Error...
> > 两行代码的问题 用了整整两天233333
> 
> 老哥NB

过奖了hhh 以后的测试和反馈主要还是靠你们

**Comment by findmio** [comment]
> > > 之前的问题是重启连接后没重置原来的弹幕容器 所以一直Error...
> > > 两行代码的问题 用了整整两天233333
> > 
> > 
> > 老哥NB
> 
> 过奖了hhh 以后的测试和反馈主要还是靠你们

大佬就是肝啊，刚看到重复推送的bug，居然都修复了了

**Comment by Billyzou0741326** [comment]
> > > > 之前的问题是重启连接后没重置原来的弹幕容器 所以一直Error...
> > > > 两行代码的问题 用了整整两天233333
> > > 
> > > 
> > > 老哥NB
> > 
> > 
> > 过奖了hhh 以后的测试和反馈主要还是靠你们
> 
> 大佬就是肝啊，刚看到重复推送的bug，居然都修复了了

hhh毕竟这程序我也在用嘛
然后不是很确定重复推送是不是完全解决了 再测几次吧

**Comment by like044041** [comment]
老哥,弹幕监控可能出问题了,舰长抽奖都没监测到,而bilibili-live-tools就可以监测到抽奖.

**Comment by Billyzou0741326** [comment]
> 老哥,弹幕监控可能出问题了,舰长抽奖都没监测到,而bilibili-live-tools就可以监测到抽奖.

查看了下数据库，确实两个小时前就丢失数据了

**Comment by Billyzou0741326** [comment]
这次的bug十分严重呢... 先停用，等我调查完再恢复

**Comment by like044041** [comment]
老哥加油

**Comment by Billyzou0741326** [comment]
> 老哥加油

谢谢

其实我早该想到的... 
这种监听方式对服务器造成的压力太大了，`tx-live-dmcmt-sv-01.chat.bilibili.com`这个服务器已经成了一发送连接请求就被拒绝的状态了

**Comment by Billyzou0741326** [comment]
没错.... b站的服务器很可能把我拉黑了23333

**Comment by Billyzou0741326** [comment]
不对... 不同的IP地址也连接不上

**Comment by like044041** [comment]
听上去不太好搞的样子,看来老哥要花点心思了.

**Comment by Billyzou0741326** [comment]
很棘手

**Comment by like044041** [comment]
老哥加油吧,也只能喊喊口号了

**Comment by Billyzou0741326** [comment]
> 老哥加油吧,也只能喊喊口号了

hhh谢谢
用了不是办法的办法... 如果再出现这种情况程序会终止的，毕竟这代表b站服务器那边不接受请求了...

**Comment by Billyzou0741326** [comment]
> 老哥加油吧,也只能喊喊口号了

诶对了 感谢反馈 看这情况如果你不提的话我要再过几天才能反应过来出问题了23333
所以我说测试和反馈果然要靠你们嘛hhhh

**Comment by like044041** [comment]
> > 老哥加油吧,也只能喊喊口号了
> 
> 诶对了 感谢反馈 看这情况如果你不提的话我要再过几天才能反应过来出问题了23333
> 所以我说测试和反馈果然要靠你们嘛hhhh

白嫖用户能做的也只有反馈了

**Comment by Billyzou0741326** [comment]
> 白嫖用户能做的也只有反馈了

所有反馈都帮了大忙了啊hhh
而且我不也白嫖吗233 一样的

**Comment by like044041** [comment]
话说老哥,明天就有大乱斗了,现在能白嫖大乱斗吗?

**Comment by Billyzou0741326** [comment]
> 话说老哥,明天就有大乱斗了,现在能白嫖大乱斗吗?

很遗憾现在还不行2333
目前不太明白怎么检测大乱斗抽奖，明天收集一下数据，看看能不能在结束之前实现

**Comment by like044041** [comment]
> > 话说老哥,明天就有大乱斗了,现在能白嫖大乱斗吗?
> 
> 很遗憾现在还不行2333
> 目前不太明白怎么检测大乱斗抽奖，明天收集一下数据，看看能不能在结束之前实现

我就随口一问,老哥你不搞也没关系的

**Comment by Billyzou0741326** [comment]
> 我就随口一问,老哥你不搞也没关系的

没事没事hhh 总归是要加上大乱斗监控的... 看看能不能这次完成

诶对了 知道活动具体什么时候开始吗  我想知道应该什么时候开始收集数据.....

**Comment by like044041** [comment]
> > 我就随口一问,老哥你不搞也没关系的
> 
> 没事没事hhh 总归是要加上大乱斗监控的... 看看能不能这次完成
> 
> 诶对了 知道活动具体什么时候开始吗 我想知道应该什么时候开始收集数据.....

应该是9号的0点开始吧 
https://live.bilibili.com/blackboard/activity-DLD.html

**Comment by Billyzou0741326** [comment]
> > > 我就随口一问,老哥你不搞也没关系的
> > 
> > 
> > 没事没事hhh 总归是要加上大乱斗监控的... 看看能不能这次完成
> > 诶对了 知道活动具体什么时候开始吗 我想知道应该什么时候开始收集数据.....
> 
> 应该是9号的0点开始吧
> https://live.bilibili.com/blackboard/activity-DLD.html

多谢多谢 我提前准备一下

**Comment by like044041** [comment]
> > > > 我就随口一问,老哥你不搞也没关系的
> > > 
> > > 
> > > 没事没事hhh 总归是要加上大乱斗监控的... 看看能不能这次完成
> > > 诶对了 知道活动具体什么时候开始吗 我想知道应该什么时候开始收集数据.....
> > 
> > 
> > 应该是9号的0点开始吧
> > https://live.bilibili.com/blackboard/activity-DLD.html
> 
> 多谢多谢 我提前准备一下

为了白嫖点辣条是真的不容易,

**Comment by Billyzou0741326** [comment]
> 为了白嫖点辣条是真的不容易,

我的初衷也是白嫖来着23333

**Comment by like044041** [comment]
> > 为了白嫖点辣条是真的不容易,
> 
> 我的初衷也是白嫖来着23333

托老哥的福,已经白嫖了不少舰长的抽奖了,我现在是几个工具轮流用,充值是没办法充值了,白嫖水平得高一点,还要防止小黑屋.

**Comment by Billyzou0741326** [comment]
> > > 为了白嫖点辣条是真的不容易,
> > 
> > 
> > 我的初衷也是白嫖来着23333
> 
> 托老哥的福,已经白嫖了不少舰长的抽奖了,我现在是几个工具轮流用,充值是没办法充值了,白嫖水平得高一点,还要防止小黑屋.

能用就好hhh 
我目前打算专攻舰长/抽奖监听，其它功能的拓展以后吧

**Comment by like044041** [comment]
> > > > 为了白嫖点辣条是真的不容易,
> > > 
> > > 
> > > 我的初衷也是白嫖来着23333
> > 
> > 
> > 托老哥的福,已经白嫖了不少舰长的抽奖了,我现在是几个工具轮流用,充值是没办法充值了,白嫖水平得高一点,还要防止小黑屋.
> 
> 能用就好hhh
> 我目前打算专攻舰长/抽奖监听，其它功能的拓展以后吧

现在这样挺好的,什么领取宝箱和心跳之类的,我找了个可以关抽奖的工具挂着,这样就不会冲突了.

**Comment by Billyzou0741326** [comment]
> > > > > 为了白嫖点辣条是真的不容易,
> > > > 
> > > > 
> > > > 我的初衷也是白嫖来着23333
> > > 
> > > 
> > > 托老哥的福,已经白嫖了不少舰长的抽奖了,我现在是几个工具轮流用,充值是没办法充值了,白嫖水平得高一点,还要防止小黑屋.
> > 
> > 
> > 能用就好hhh
> > 我目前打算专攻舰长/抽奖监听，其它功能的拓展以后吧
> 
> 现在这样挺好的,什么领取宝箱和心跳之类的,我找了个可以关抽奖的工具挂着,这样就不会冲突了.

确实hhh 互补刚好

**Comment by Billyzou0741326** [comment]
> 话说老哥,明天就有大乱斗了,现在能白嫖大乱斗吗?

实现了...

**Comment by like044041** [comment]
> > 话说老哥,明天就有大乱斗了,现在能白嫖大乱斗吗?
> 
> 实现了...

老哥你是真的6

**Comment by Billyzou0741326** [comment]
> 老哥你是真的6

过奖了hhh

其实如果你不提的话我可能根本想不到要加上大乱斗的监听2333
而且多亏二狗大佬提供的资源才能这么快实现hhh 所以基本上是你们推动项目完善的…
