### ISSUE TITLE
筛选监听房间的算法、获取完整的直播列表

### ISSUE THREAD

**Issue by Billyzou0741326** [Billyzou0741326/bilibili-live-monitor-js#2]
目前的直播列表取自这个[API](https://api.live.bilibili.com/room/v3/area/getRoomList?parent_area_id=0&page=1&page_size=99&sort_type=online)
```
但是这里的列表极度不完整 关注的好几间直播中的直播间都没在返回值里(所有页数的返回都没有) 简直无法形容
哪位大佬如果有这方面的建议 希望能指教一下...

过滤掉人气过低的直播间应该可以通过心跳进行 本来是这么想的 
但有次b站人气值显示错误 大部分直播间都显示1 然后就不监听了23333
同上 如果有建议 不胜感激
```
### 2019-12-16  
- 监听所有直播中、且人气值高于20的直播间
- 永久监听大航海榜上所有直播间
- 记录各个直播间的上船个数，大于3加入永久监听列表
- 不在永久列表中的直播间，下播5分钟后停止监听

**Comment by Billyzou0741326** [comment]
万分感谢[YJ](https://github.com/yjqiang)大佬的动态+静态方法 以及从多个来源取得候选房间的思路

毕竟现在50%的舰长覆盖率有点少呢 上千个房间也只有这种覆盖率的话说明现在的算法不是最佳方案

**Comment by like044041** [comment]
看来又要升级了

**Comment by Pearlulu** [comment]
网页全部直播那里的api还用的v1，v1v3同时用不知道会不会互补。。我感觉按分区分别获取的列表挺准的啊

**Comment by Billyzou0741326** [comment]
嗯，v1v3都用是个不错的方法，可以写进去

按分区获取的高能房间应该没问题… 舰长房间的选取就要另外想办法了

**Comment by Billyzou0741326** [comment]
@Billyzou0741326 
## API
- ~~[房间舰长数量](https://api.live.bilibili.com/xlive/app-room/v1/guardTab/topList?roomid=9758780&page=1&ruid=3622227&page_size=1)~~
- [全站大航海排行](https://api.live.bilibili.com/rankdb/v1/Rank2018/getWebTop?type=sail_boat_value&area_id=&page=1&is_trend=1&page_size=20)
- [全站元气排行](https://api.live.bilibili.com/rankdb/v1/Rank2018/getWebTop?date=week&type=master_vitality_2018&area_id=0&page=1&is_trend=1&page_size=20) (取自[排行榜页面](https://live.bilibili.com/p/eden/rank#/childnav/vitality/0))

**Comment by Billyzou0741326** [comment]
@Billyzou0741326 备忘
[扭蛋机](http://live.bilibili.com/pages/playground/index#capsule-toy)
