### ISSUE TITLE
无法参与抽奖

### ISSUE THREAD

**Issue by like044041** [Billyzou0741326/bilibili-live-monitor-js#68]
老哥你看看,这是我个人问题吗
![20191229234140](https://user-images.githubusercontent.com/33434924/71559094-03c5a680-2a95-11ea-848f-418a157b96e0.png)

**Comment by Billyzou0741326** [comment]
这是python版我写的请求限制的问题
不限制的话就会风控ip地址了

**Comment by Billyzou0741326** [comment]
看起来请求控制限制得太严格了  导致每秒15个请求的话确实领不完 这几天的百连千连

**Comment by Billyzou0741326** [comment]
实在抱歉hhh 我翻车了

**Comment by Billyzou0741326** [comment]
车祸现场异常惨烈2333
