### ISSUE TITLE
Bug: 新版412风控过于频繁

### ISSUE THREAD

**Issue by Billyzou0741326** [Billyzou0741326/bilibili-live-monitor-js#91]
发现没有特别好的对付412的方法 wsl
试试这样能不能修好吧 应该是没用上http agent的原因

**Comment by Billyzou0741326** [comment]
昨天又被控了一次 今天测下这个修复 没问题的话就ok了

**Comment by Billyzou0741326** [comment]
结果还是没能解决呢... 再测一次吧

**Comment by Pearlulu** [comment]
> 结果还是没能解决呢... 再测一次吧

今晚2台用新版的都被风控了，一台挂了，一台不更新房间了

**Comment by Pearlulu** [comment]
要不试试间隔1秒以上请求一次API，持续一页一页获取房间列表，完成也差不多两分钟，然后把重复的房间去掉。主要是不知道这个风控是怎么判定的，只能慢慢试了。

**Comment by Billyzou0741326** [comment]
1秒长了点 这个度具体在哪不太好把控...

昨晚又炸了
今天的话用上支线合并、请求限制这些 看下能不能稳吧
